- 👋 Hi, I’m @faithiyanuekun22
- 👀 I’m interested in roqqu.com
- 🌱 I’m currently learning bitcoin.com
- 💞️ I’m looking to collaborate on Facebook
- 📫 How to reach me: ekundayoiyanufaith@gmail.com
- 😄 Pronouns: faithiyanuekun22
- ⚡ Fun fact: fast withdrawal
- 🌐 Website: https://www.app.roqqu.com

<!---
faithiyanuekun22/faithiyanuekun22 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
https://app.roqqu.com
